# Generated by Django 5.0.2 on 2024-03-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskTitle', models.CharField(max_length=100)),
                ('taskDescription', models.CharField(max_length=100)),
                ('isCompleted', models.BooleanField(default=False)),
                ('taskAssignDate', models.DateField()),
            ],
        ),
    ]
