# Generated by Django 5.0.2 on 2024-03-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskModel', '0001_initial'),
        ('taskCategory', '0002_remove_taskcategory_taskmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='taskCategory',
            field=models.ManyToManyField(to='taskCategory.taskcategory'),
        ),
    ]
